name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      id: setupJava
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      if: steps.checkout.outcome == 'success'
    - name: test
      id: test
      run: mvn test --file pom.xml
      if: steps.setupJava.outcome == 'success'
    - name: package
      if: steps.test.outcome == 'success'
      run: mvn install -Pproduction
